skinparam backgroundColor #EEEBDC

== Messaging System ==

box "List of Users" #LightBlue
  participant Input
end box

box "Ingest Process" #White
  collections Ingest
end box

box "Message Store" #Yellow
  database DB
end box

box "Batch Process" #White
  collections Batch
end box

box "Remote System" #LightGreen
  participant API
end box
